React carousel component
edtan094/c1121-code-solutions pull request #125
Opened 2022-02-06 19:03 UTC by edtan094

![react-carousel-component](https://user-images.githubusercontent.com/90667339/152697143-8bcc9b6f-bdd1-4da7-a8ca-fd671212f104.gif)

2022-02-07 18:27 UTC, thebearingedge requested changes
Ok, good, but we need to reorganize some stuff to make this more React-y.

2022-02-07 18:27 UTC, thebearingedge commented on react-carousel-component/src/carousel.jsx
> +    if (index > 4) {
We don't know how many images the carousel will deal with so you'll have to remove any hard-coded numbers like this.

2022-02-07 18:27 UTC, thebearingedge commented on react-carousel-component/src/carousel.jsx
> +    this.componentDidMount();
Generally we never call lifecycle methods like this. Instead define a separate custom method that you can call from within here and componentDidMount

2022-02-07 18:27 UTC, thebearingedge commented on react-carousel-component/src/carousel.jsx
> +      }
We don't manipulate the DOM like this in React. Instead, pass the correct props to your React elements in `render`

2022-02-11 15:19 UTC, thebearingedge requested changes
Ok, fantastic, but the list of images should be passed to the component in `index.jsx` as a prop.

2022-02-11 21:14 UTC, edtan094 commented
![react-carousel-updated](https://user-images.githubusercontent.com/90667339/153671068-cfff13eb-17dd-4787-9d1b-5a1b42b11648.gif)

2022-02-14 02:12 UTC, thebearingedge approved these changes

2022-02-14 17:49 UTC, merged