Completed css-brochure-form exercise. Edwin Tan
edtan094/c1121-code-solutions pull request #16
Opened 2021-12-02 18:54 UTC by edtan094

![image](https://user-images.githubusercontent.com/90667339/144485083-4cbf4c48-2bac-4a54-920c-7799913df410.png)

2021-12-02 18:56 UTC, codingcodymiller requested changes
Hey Edwin! your form is too wide as compared to the example, please revise and resubmit with a new screenshot

2021-12-02 19:05 UTC, edtan094 commented
![image](https://user-images.githubusercontent.com/90667339/144486588-3d4a8fc5-9d38-4841-a8c4-94eecf713ca6.png)
Screenshot attached

2021-12-02 20:26 UTC, codingcodymiller requested changes
Great work! One note for you:

2021-12-02 20:26 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +}
These class names aren't very descriptive of their purpose, try to use a name that better articulates what they are for.

2021-12-03 01:19 UTC, codingcodymiller approved these changes
Great work!!

2021-12-03 01:26 UTC, merged