Css ecommerce page. Edwin Tan
edtan094/c1121-code-solutions pull request #34
Opened 2021-12-10 01:52 UTC by edtan094

![image](https://user-images.githubusercontent.com/90667339/145503927-83cbeb51-35e2-4253-b73d-503ce4f429f8.png)

2021-12-10 23:04 UTC, codingcodymiller requested changes
Hey Edwin, there is too much vertical space between your lines of text as compared to the example, please revise.

2021-12-13 18:27 UTC, codingcodymiller requested changes
Hey Edwin! Please upload a screenshot fo your revision, and send me a Slack message to let me know when you have done so.

2021-12-13 19:15 UTC, edtan094 commented
Hey Cody, attached is the new screenshot
![image](https://user-images.githubusercontent.com/90667339/145873984-54ceb7cb-ccc7-4261-8810-33e417946ea9.png)

2021-12-14 00:45 UTC, codingcodymiller approved these changes

2021-12-14 01:50 UTC, merged